scalar Date

type User {
  id: ID
  name: String
  email: String
  password: String
  create_at: Date
  update_at: Date
}

input CreateUserInput {
  name: String
  email: String
  password: String
}

type Query {
  users: [User!]!
}

type Mutation {
  createUser(input: CreateUserInput!): User!
}
